version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${APP_HOST_PORT}:80
    volumes:
      - ./src:/var/www/html/
  db-server:
    # root:${DB_PASSWORD}@${DB_CONTAINER_NAME}
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - ${DB_ADMIN_HOST_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_CONTAINER_NAME}

volumes:
  mysql-data: