version: "3.1"

volumes:
  data:

services:
  php-app-init:
    image: composer
    volumes:
      - ./app/lib:/app
    command: composer update
  php-apache:
    build:
      context: ./app
      dockerfile: php-apache.dockerfile
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/var/www/html/
    depends_on:
      - php-app-init
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
  adminer:
    depends_on:
      - database
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
